# Generic Resume/CV Data File
# Fill in your own details using this template.

experience_details:
  - position: "Your Job Title (e.g., Software Engineer)"
    company: "Company Name"
    employment_period: "Month Year - Present"
    location: "City, Country | Remote"
    key_responsibilities:
      - "Describe your key accomplishment #1. Start with an action verb and quantify your impact. (e.g., Developed a feature that increased user engagement by 15%)."
      - "Describe your key accomplishment #2. Focus on the technologies used and the problem you solved."
      - "Describe your key accomplishment #3. Mention any collaboration or leadership roles."
      - "Describe your key accomplishment #4."
    skills_acquired:
      - "Skill A (e.g., Android Development)"
      - "Skill B (e.g., Cloud Development)"
      - "Skill C (e.g., Data pipeline construction)"
      - "WebRTC"
      - "Serverless architecture"
      - "Java"
      - "JavaScript"
      - "Python"
      - "Kotlin"
      - "NodeJs"
      - "SQL/NoSQL"
      - "AWS"

  - position: "Another Job Title (e.g., Web Developer)"
    company: "Previous Company Name"
    employment_period: "Month Year - Month Year"
    location: "City, Country"
    key_responsibilities:
      - "Built a [type of system] using [technology]. (e.g., Built a web-based management system using PHP Laravel)."
      - "Developed [type of application] for [platforms]. (e.g., Developed a cross-platform mobile app using React Native)."
      - "Implemented a [project type] with [technologies]. (e.g., Implemented a PoC for an intranet chat app with Android and .NET)."
    skills_acquired:
      - "Web Development"
      - "Mobile Development"
      - "React Native"
      - "Backend Development (Python, PHP)"
      - ".NET Framework"
      - "Scalable Software Design"

personal:
  name: "John"
  last_name: "Doe"
  full_name: "John Doe"
  location: "City, Country"
  email: "your.email@example.com"
  github: "github.com/yourusername"
  linkedin: "linkedin.com/in/yourusername/"
  phone: "+1 (123) 456-7890"
  description: "A brief, compelling summary of your professional profile, highlighting your key skills, experience, and career goals."

education:
  - degree: "Your Degree | Your Major (e.g., Master of Science | Computer Science)"
    dates: "Month Year - Month Year"
    institution: "University Name"
    location: "City, Country"
    details: "Briefly describe your thesis, capstone project, or relevant academic achievements."
  - degree: "Your Degree | Your Major (e.g., Bachelor of Engineering | Computer Engineering)"
    dates: "Month Year - Month Year"
    institution: "University Name"
    location: "City, Country"
    details: "Briefly describe your thesis, capstone project, or relevant academic achievements."

certifications:
  - name: "Name of Certification (e.g., AWS Certified Solutions Architect)"
    description: "Optional: Add a brief description or link to the credential."
    date: "Month Year"
  - name: "Name of Another Certification (e.g., Google Associate Cloud Engineer)"
    description: "Optional: Add a brief description or link."
    date: "Month Year"

core_skills:
  - "Python"
  - "Kotlin"
  - "Cloud Computing"
  - "WebRTC"
  - "JavaScript"
  - "C++"
  - "C"
  - "CI/CD"
  - "Backend Engineering"
  - "Android Development"
  - "React Native"
  - "React"
  - "Serverless"
  - "REST API"
  - "AWS"
  - "Data Processing & Analysis"
  - "Machine Learning"
  - "Java"
  - "Web Development"
  - "Database Management"
  - "Communication & Collaboration"
  - "Project Management"
  - "SQL"
  - "NoSQL"
  - "Node.js"
  - "Microservices"
  - "DynamoDB"
  - "Google Cloud Platform"